### ISSUE TITLE
Issue installing ggplot with Python 3.6

### ISSUE THREAD

**Issue by allyelsey** [conda-forge/ggplot-feedstock#14]
Cannot install the 3.6 ggplot package from the conda-forge channel.

On Mac:
When I try to install ggplot into my root env (fresh Anaconda 4.4 install) it throws this error:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator
  - ggplot
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

When installing into a conda env with just python 3.6 and dependencies it installs correctly. 

I am able to recreate the same behavior on Windows.

**Comment by ijstokes** [comment]
@allyelsey what makes you think that this is a problem with the conda-forge feedstock for ggplot?

Does this command work for you?

```
conda create -n ggpy36 -c conda-forge python=3.6 ggplot
```

It works for me.  If I had to guess I'd say that the problem is that conda is identifying a conflict between `ggplot` and `anaconda-navigator`.  Since Navigator is already installed it will prevent `ggplot` from being installed (doing so would break Navigator).  Again: just a guess.
